### ISSUE TITLE
Move bar plot SVGs into viewboxes so they scale appropriately

### ISSUE THREAD

**Issue by RosyGraph** [RosyGraph/datavis-final-project.github.io#18]
Currently, the SVGs overflow the page vertically, ~~and only one bar chart is shown per row~~.

**Comment by RosyGraph** [comment]
I have previously used something like the following in the past. Leaving this here for reference.

```css
      .svg-container {
        display: flex;
        flex-direction: row;
        position: relative;
        width: 100%;
      }
      .svg-content {
        display: block;
        width: 100%;
      }
```
